iri: 8370ac9f-e9f2-4cf8-898f-8c08684adb11
projectIri: e9875c13-3dbb-4239-a0ac-6a245d1a63aa
types:
  - http://dataspecer.com/resources/local/package
userMetadata:
  label:
    cs: "DCAT-AP-CZ: Základní datový model pro katalogy dat"
    en: "DCAT-AP-CZ: Basic data model for data catalogs"
  description: {}
  importedFromUrl: https://ofn.gov.cz/dcat-ap-cz/draft/cs/
  documentBaseUrl: https://ofn.gov.cz/dcat-ap-cz/draft/cs/
metadata:
  creationDate: 2026-04-04T21:00:47.652Z
  modificationDate: 2026-04-04T21:01:37.276Z
_version: 1
_exportVersion: 2
_exportedAt: 2026-04-13T07:52:59.475Z
_exportedBy: http://localhost:3100
