iri: 547c8dbc-21f5-435d-8798-4adf7ead0078
projectIri: 21108878-6cec-4f45-b3d2-f38398073058
types:
  - http://dataspecer.com/resources/local/package
userMetadata:
  label:
    cs: Výchozí aplikační profil DCAT 3
    en: DCAT 3 Default Application Profile
  description: {}
  importedFromUrl: https://mff-uk.github.io/specifications/dcat-dap/
  documentBaseUrl: https://mff-uk.github.io/specifications/dcat-dap/
metadata:
  creationDate: 2026-04-04T21:00:43.247Z
  modificationDate: 2026-04-04T21:01:31.494Z
_version: 1
_exportVersion: 2
_exportedAt: 2026-04-13T07:52:59.428Z
_exportedBy: http://localhost:3100
