iri: 4fb026e0-3deb-426e-a670-91ad7dfcc09a
projectIri: 1838e110-8e88-4051-9579-dd46c709eab4
types:
  - http://dataspecer.com/resources/local/package
userMetadata:
  label:
    cs: DCAT-AP 3.0.1 na základě DCAT 3 DAP
    en: DCAT-AP 3.0.1 based on DCAT 3 DAP
  description: {}
  importedFromUrl: https://mff-uk.github.io/specifications/dcat-ap/
  documentBaseUrl: https://mff-uk.github.io/specifications/dcat-ap/
metadata:
  creationDate: 2026-04-04T21:00:43.186Z
  modificationDate: 2026-04-04T21:01:31.500Z
_version: 1
_exportVersion: 2
_exportedAt: 2026-04-04T21:03:52.873Z
_exportedBy: http://localhost:3100
