iri: 2efa68f1-651f-4e27-85cb-9363b2dd1858
projectIri: 773659a7-a76c-4e30-aa48-6a7372a45bbd
types:
  - http://dataspecer.com/resources/local/package
userMetadata:
  label:
    cs: Výchozí aplikační profil DCAT 3
    en: DCAT 3 Default Application Profile
  description: {}
  importedFromUrl: https://mff-uk.github.io/specifications/dcat-dap/
  documentBaseUrl: https://mff-uk.github.io/specifications/dcat-dap/
metadata:
  creationDate: 2026-04-04T20:44:46.807Z
  modificationDate: 2026-04-04T20:54:31.634Z
_version: 1
_exportVersion: 2
_exportedAt: 2026-04-04T20:54:37.485Z
_exportedBy: http://localhost:3100
