iri: ea8a7f62-5740-48e3-9797-efad73c56c9f
projectIri: 22e59f2c-e892-42b2-9c80-e4b31391685a
types:
  - http://dataspecer.com/resources/local/package
userMetadata:
  label:
    en: DCAT-AP HVD 3.0.0
  description: {}
  importedFromUrl: https://mff-uk.github.io/specifications/dcat-ap-hvd/
  documentBaseUrl: https://mff-uk.github.io/specifications/dcat-ap-hvd/
metadata:
  creationDate: 2026-04-04T21:00:43.143Z
  modificationDate: 2026-04-04T21:01:31.504Z
_version: 1
_exportVersion: 2
_exportedAt: 2026-04-13T07:52:59.442Z
_exportedBy: http://localhost:3100
